In [2]:
import numpy as np

In [35]:
from skimage.transform import ProjectiveTransform

In [45]:
ProjectiveTransform(np.linalg.inv(ProjectiveTransform().params))

In [43]:
ProjectiveTransform().params

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
print(U.shape)
print(S.shape)
print(V.shape)

(8, 8)
(8,)
(9, 9)


In [26]:
U

array([[-0.05365186,  0.29872814, -0.15371836,  0.42186184, -0.46739871,
        -0.27630559, -0.04027389, -0.16175327, -0.61943021],
       [-0.0479212 , -0.59061694,  0.38576805, -0.24766208,  0.11521196,
        -0.08331048,  0.06097755,  0.12572037, -0.63165132],
       [ 0.19162116, -0.14735372, -0.32868393, -0.31452111, -0.62389719,
         0.12440528,  0.18149963,  0.54336017,  0.041289  ],
       [ 0.27635929,  0.13051854,  0.36268748, -0.05357721, -0.11692664,
        -0.30729823, -0.74836234,  0.30425946,  0.10702182],
       [-0.25596988, -0.22167179, -0.61528673,  0.09166699,  0.37517942,
        -0.48031369, -0.17422839,  0.31060612, -0.00824045],
       [ 0.20224829, -0.17528428, -0.08911791,  0.59151536,  0.17122284,
         0.6144867 , -0.21595447,  0.30884388, -0.14699178],
       [-0.39370927,  0.24019982, -0.24471967, -0.47836799,  0.03037   ,
         0.44352454, -0.46016351, -0.11290674, -0.27647541],
       [ 0.65720243, -0.28385981, -0.37424497, -0.16074857,  0

In [29]:
A.shape

(9, 8)

In [34]:
A @ V[-1]

array([-2.73478938e-16, -1.42813544e-16, -5.86503905e-16,  4.11816814e-16,
       -1.41166865e-16,  1.02868665e-16, -1.10981150e-16, -1.42813544e-16])

In [46]:
A = np.zeros((2, 2))
B = np.zeros((2, 2))

In [47]:
np.concatenate([A, B])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
A = np.asarray([[1, 0], [1, 0]])

In [50]:
A.max(axis=0)

array([1, 0])